# fly.toml app configuration file generated for perrito-profile on 2025-12-17T10:51:28-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'perrito-profile'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 4002
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  MONGO_URI = "mongodb+srv://leonardopavez_db_user:gX8YRO8ARUIdC1TY@cluster0.cbahedj.mongodb.net/perritos"
  JWT_SECRET = "Hw48T3V54FgrIiIEm7Ga7mRCoB3GBZW6Q4JQDySCAsCT5xPGAPurdT8sfM6wCWZc" 
  

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
